export const PURPOSE_CODE_UPDATE_EVENT = "PURPOSE_CODE_UPDATE_EVENT";
export const INVOICE_MARKED_AS_PAID_EVENT = "INVOICE_MARKED_AS_PAID_EVENT";

export const SUB_NAV_BAR_REMOVAL_EVENT = "SUB_NAV_BAR_REMOVAL_EVENT_:id";

export const REDIRECT_TO_NEXT_FUNDING_EVENT = "REDIRECT_TO_NEXT_FUNDING_EVENT";

export const SELECT_INVOICE_IN_MAPPING_TABLE_EVENT = "SELECT_INVOICE_IN_MAPPING_TABLE_EVENT";

export const E_INVOICE_ENABLED_EVENT = "E_INVOICE_ENABLED_EVENT";

export const INVOICE_EMAIL_SENT = "INVOICE_EMAIL_SENT";

export const PROOF_SUBMITTED = "PROOF_SUBMITTED";

/**
 * Currently only used to make `isLoading` true in invoices/index.tsx component
 */
export const CLEAR_ALL_FILTERS = "CLEAR_ALL_FILTERS";

export const RECURRING_INVOICE_CONFIG_UPDATE = "RECURRING_INVOICE_CONFIG_UPDATE";
