export const TransactionDocType = {
  SKYDO_RECEIPT: "SKYDO_RECEIPT",
  FIRA_DOCUMENT: "FIRA_DOCUMENT",
  PAYMENT_DETAILS: "PAYMENT_DETAILS",
  INVOICE_FILE: "INVOICE",
};

export const SKYDO_INVOICE_IDENTIFIER = ["CHALLAN", "CHALLAN_RECURRING"];
