export const popupStateType = {
  DEFAULT: "DEFAULT",
  SKIP_DEFAULT: "SKIP_DEFAULT",
  EDIT_DEFAULT: "EDIT_DEFAULT",
  REMOVE_DEFAULT: "REMOVE_DEFAULT",
  ADD_PC_INVOICE: "ADD_PC_INVOICE",
  EDIT_PC_INVOICE: "EDIT_PC_INVOICE",
};
