const BE_ROUTES = {
  T_C_ACCEPT: "/swagat/api/accept/tnc_privacy",
  CREATE_EXPORTER_PAN: "/swagat/api/create_exporter_with_pan",
  SUBMIT_COMPANY_DETAILS: "/swagat/api/submit/company_details",
  UPDATE_BUSINESS_NAME: "/swagat/api/update/business_name",
  SUBMIT_PHONE_NO: "swagat/api/submit/mobile",
  UPDATE_WHATSAPP_CONSENT: "/swagat/api/update/whatsapp_consent",
  SUBMIT_GSTID: "/swagat/api/submit/gstin",
  SUBMIT_BUSINESS_DESCRIPTION: "swagat/api/industry_types",
  PAN_OCR: "/swagat/api/ocr/pan",
  USER_PAN_PROFILE: "/swagat/api/user_pan_profile_details",
  INITIATE_PHONE_OTP: "/swagat/api/initiate/user_phone_verification",
  VERIFY_DIRECTOR_OTP_SAVE_DATA: "/swagat/api/verify/user_phone_otp",
  UPDATE_UBO_DETAILS: "/swagat/api/update/ubo_details",
  UPDATE_UBO_DETAILS_V2: "/swagat/api/v2/update/ubo_details",
  UPDATE_AND_VERIFY_ALTERNATE_UBO_PAN: "/swagat/api/update_ubo_pan",
  CAPTURE_USER_DECLARATION: "/declaration/api/submit",
  CAPTURE_SOLE_PROP_DECLARATION: "/declaration/api/submit/soleprop",
  CAPTURE_VKYC_DECLARATION: "/declaration/api/submit/vkyc",
  BANK_VERIFICATION: "/swagat/api/bank_account/verification",
  BANK_ACCOUNT_SUBMIT: "/swagat/api/bank_account_submit",
  PROPRIETORSHIP_ACKNOWLEDGEMENT: "/swagat/api/accept/proprietorship",
  FREELANCER_ACKNOWLEDGEMENT: "/swagat/api/accept/freelancing",
  INFORM_TEAM_DOC_ISSUE: "/swagat/api/inform_team_about_doc",
  GENERATE_AADHAAR_OTP: "/swagat/api/initiate/aadhaar_verification",
  VERIFY_AADHAAR_OTP: "/swagat/api/download/aadhaar_xml",
  SUBMIT_DIRECTOR_DETAILS: "/swagat/api/ubo_pan_detail/submit",
  SUBMIT_WEBSITE_DETAILS: "/swagat/api/submit/website",
  CREATE_VIRTUAL_ACCOUNT: "/munshi/initiate/virtual/account",
  MARK_INVOICE_AS_PAID: "/invoice/mark-invoice-paid-outside-skydo",
  MARK_INVOICE_FULLY_PAID: "/invoice/:invoiceId/mark-fully-paid",
  MARK_INVOICE_AS_ARCHIVED: "/invoice/mark-invoice-archive",
  EXECUTE_INSTANT_SETTLEMENT: "/instant/settlement/execute",
  /** Called on app load to run settlement date calculation before any settlementDate is used elsewhere */
  REVISE_SETTLEMENT_DATE: "transaction/exporter/revise-settlement-date",
  FETCH_FX_RATE: "/fxrates/live?baseCurrency=USD&targetCurrency=INR",
  GRAPH_QL: "/graphql",
  GRAPH_QL_DASHBOARD: "/graphql/dashboard",
  TOGGLE_EMAIL_CONFIG: "/importer_emails/config",
  SAVE_IMPORTER_EMAILS: "/importer_emails/emails",
  SEND_PC_EMAIL: "/importer_emails/payment_confirmation",
  SEND_SAMPLE_PC_EMAIL: "/importer_emails/payment_confirmation/sample",
  GET_PREFERRED_EMAILS_FOR_IMPORTER: "/importer_emails/preferred/:invoiceId",
  PUBLIC_GRAPH_QL_DASHBOARD: "pub/graphql/dashboard",
  FETCH_FX_PRICING: "/dashboard/calculation?transactionId=:transactionId",
  GENERIC_DOWNLOADER: "/generic_downloader",
  GENERIC_DOWNLOADER_AVAILABILITY: "/generic_downloader/availability",
  INVOICE_SPECIFIC_PC: "/invoice/purpose-code/",
  DELETE_DEFAULT_PC: "/default-purpose-code",
  CHANGE_DEFAULT_PC: "/default-purpose-code/:selectedPC",
  GET_LOGGEDIN_USER_DETAILS: "/swagat/api/get_loggedin_user_details",
  REGISTER: "user/management/register",
  SECONDARY_USER_DETAILS: "/swagat/api/secondary_user/exporter_details",
  SECONDARY_USER_ACCESS_REQUEST: "/swagat/api/secondary_user/access_request",
  FETCH_PRE_FX_PRICE: "munshi/pricing/prefx",
  FETCH_FX_RATE_LIST: "/fxratelist",
  FETCH_SUMMARY_DATA: "munshi/summary",
  CONFIRM_N_CONTINUE_DEED: "/swagat/api/accept/notarized_deed",
  DEED_FILE_UPLOAD: "/swagat/api/upload/partnership_deed",
  EXPORTER_KYC_DOC_UPLOAD: "/swagat/api/upload/exporter_kyc_document",
  BANK_STATEMENT_VERIFY: "/swagat/api/verify/bank_statement",
  IMPORTER_DOC_UPLOAD: "/dashboard/upload/importer-doc",
  IMPORTER_DOC_DELETE: "/dashboard/delete/importer-doc",
  CONFIRM_N_CONTINUE_EXPORTER_KYC_DOC: "/swagat/api/submit/exporter_kyc_document",
  MARK_EXPORTER_DOCS_ACTIVE: "/swagat/api/update/exporter_kyc_active_document",
  FETCH_FILTERED_INVOICES: "/invoice/filter",
  FETCH_MONTHLY_SUMMARY: "/munshi/summary/month?startDate=:startDate&endDate=:endDate",
  FETCH_IMPORTER_SUMMARY: "/munshi/summary/importer-level?startDate=:startDate&endDate=:endDate",
  FETCH_IMPORTER_MONTHLY_SUMMARY:
    "/munshi/summary/importer/month?startDate=:startDate&endDate=:endDate&importerId=:importerId",
  CREAT_NPS_CSAT_FEEDBACK: "/swagat/api/nps-csat/create",
  UPDATE_NPS_CSAT_FEEDBACK: "/swagat/api/nps-csat/update",
  EMAIL_SUBSCRIPTION: "subscribe/email",
  PAYOUTS_WAITLIST: "waitlist/subscribe/payouts",
  FETCH_IMPORTER_CURRENCY_LEVEL_SUMMARY:
    "/munshi/summary/importer/currency-level?startDate=:startDate&endDate=:endDate&importerId=:importerId",
  FETCH_IMPORTERS: "/munshi/importers",
  SUBMIT_ANALYTICS_FEEDBACK: "/munshi/summary/feedback",
  PAYMENT_METHOD_FEEDBACK: "/payment-link/request-methods",

  GENERATE_DIGILOCKER_AADHAAR_LINK: "/swagat/api/initiate/digilocker_aadhaar",
  VERIFY_DIGILOCKER_AADHAAR_LINK: "/swagat/api/download/digilocker_aadhaar",
  MAP_FUNDING_TO_INVOICE: "invoice/exporter/map-funding-to-invoice",
  MAP_MASTER_FUNDING_TO_INVOICE: "invoice/exporter/map-master-funding-to-invoice",
  NEFT_IN_PROGRESS: "/swagat/api/neft_in_progress_summary",
  VERIFY_BANK_ACCOUNT_VIA_EMAIL: "/swagat/api/bank_account/verify_via_email",
  ACTIVATE_BANK_ACC: "/swagat/api/bank_account/activate",
  ACTIVATE_AUD_ACC: "/bc/fetch/virtual_account_details",

  FETCH_VIRTUAL_ACCOUNTS: "dashboard/public-virtual-accounts",
  UPDATE_COMPANY_LOGO: "dashboard/update-company-logo",
  FILE_DOWNLOAD_PIPE_API: "/api/route/bulk_download?path=:path",
  GENERIC_FILE_DOWNLOAD: "/generic_downloader/:downloadDocType/:entityType/:entityId",
  PUBLIC_ACCOUNT_URL: "dashboard/public-accounts-url",

  FETCH_DATA_FOR_DASHBOARD: "/api/dashboard-data",
  FETCH_BALANCE_DATA: "/api/balance-data",
  FETCH_BALANCE_ONLY: "/api/balance",
  GET_DRAFT_OUTPAY: "/api/balance/draft-outpay",
  /** BFF → backend (exporter-balance service) */
  WITHDRAW_INITIATE: "/exporter-balance/withdraw/initiate",
  WITHDRAW_PROCESS: "/exporter-balance/withdraw/process",
  CREATE_DRAFT_OUTPAY_IDENTIFIER: "/exporter-balance/outpay/create-draft-identifier",
  OUTPAY_VERIFY_AADHAAR: "/exporter-balance/outpay/verify-aadhaar",
  FILL_DRAFT_OUTPAY_DETAILS: "/exporter-balance/outpay/fill-draft-details",
  /** BFF → backend: validate US ACH routing number */
  OUTPAY_BANK_INFO: "/exporter-balance/outpay/bank-info",
  PINCODE_REGISTRY_SEARCH: "/pincode/registry/search",
  OUTPAY_INVOICE_UPLOAD: "/outpay-invoice/exporter/upload",
  FETCH_DATA_FOR_FUNDING_MAPPING: "/api/funding-invoice-mapping",
  UPLOAD_INVOICE: "/invoice/exporter/upload",

  FETCH_IMPORTERS_LIST: "/munshi/importers",
  FETCH_PARSED_INVOICE_DATA: "/api/invoice/ocr-parsed",

  PARSE_INVOICE: "invoice/exporter/parse-invoice",
  // reminder routes
  SEND_REMINDER_EMAIL: "reminder/invoice/:invoiceId",
  REMINDERS_HISTORY: "/reminder/history/invoice/:invoiceId",
  REMINDERS_PREFERRED_EMAILS: "reminder/emails/invoice/:invoiceId",
  REMINDER_BANK_ACCOUNT_FIELDS: "/reminder/bank/account/fields/:invoiceId",

  // CLIENT LEDGER APIs
  CLIENT_LEDGER_EMAIL_HISTORY: "/client-ledger/history/:importerId",
  CLIENT_LEDGER_EMAIL: "/client-ledger/email",
  CLIENT_LEDGER_PREFERRED_EMAILS: "/client-ledger/emails/:importerId",
  CLIENT_LEDGER_SUMMARY: "/client-ledger/summary/:importerIdentifier",

  // create INVOICE APIs

  FETCH_NEW_INVOICE_PAGE_DATA: "/api/create-invoice/get-invoice-details",
  GET_INVOICE_DETAILS: "graphql/challan",
  GET_COUNTRY_MASTER_LIST: "challan/country/list",
  UPDATE_INVOICE_LOGO: "/challan/update/company/logo",
  UPDATE_NEW_INVOICE: "/api/create-invoice/update-invoice",
  MARK_AS_SENT: "challan/mark/as/sent",
  UPDATE_BILL_FROM: "challan/update/bill/from",
  UPDATE_BILL_TO: "challan/update/bill/to",
  GET_GSTIN_DETAILS: "/challan/gstin/details/:gstin",
  GET_PLACE_OF_SUPPLY: "/challan/state/from/:pinCode",
  GET_COUNTRY_LIST: "/challan/list/of/countries",
  GET_PAN: "challan/fetch/pan",
  UPDATE_INVOICE_ITEMS: "/challan/update/items",
  UPDATE_BANK_ACCOUNT: "/challan/update/bankaccount",
  UPDATE_BANK_ACCOUNT_FROM_ITEMS: "/challan/items/update/bankaccount",
  CLEAR_BANK_ACCOUNT_FROM_ITEMS: "/challan/items/clear/bankaccount",
  UPDATE_OTHER_DETAILS: "/challan/update/other/details",
  DELETE_INVOICE: "challan/delete/invoice",
  CHALLAN_CREATE_INVOICE: "challan/create/invoice",
  CHALLAN_FINALIZE_INVOICE: "challan/finalize/invoice",
  CHALLAN_EDIT_INVOICE: "challan/edit/invoice",
  GET_NUMBER_OF_DRAFT_INVOICES: "challan/number/invoices",
  SKIP_E_INVOICE: "einvoice/skip/pop/up",
  SAVE_E_INVOICE_CREDS: "challan/save/einvoice/credentials",
  UPDATE_E_INVOICE: "challan/finalize/invoice/file",
  CREATE_DUPLICATE_INVOICE: "challan/invoice/duplicate/create",
  EDIT_DUPLICATE_INVOICE: "challan/invoice/duplicate/edit",
  CREATE_INVOICE_FOR_IMPORTER: "challan/client/create-invoice-by-client?importerId={{importerId}}",
  CHALLAN_UPSERT_IMPORTER: "/challan/client/update-client-info",
  MARK_USER_SKIP_ACTION_DONE: "/user-skip/mark",
  CHECK_USER_SKIP_ACTION_DONE: "/user-skip/check",
  CHECK_USER_PROCESS_STATUS: "/challan/bank-details/first-time-user",
  MARK_USER_PROCESS_COMPLETED: "/challan/bank-details/mark-user-completed",

  // Invoice Details
  FETCH_INVOICE_DETAILS: "/api/route/invoice_details",
  FETCH_BALANCE_INVOICE_SUMMARY: "/api/balance-invoice-summary",
  FETCH_INVOICE_LIST_AND_SUMMARY_HOME: "/api/route/invoice_home_data",
  TEST_TRANSACTION_SKIP_TUTORIAL: "test/transaction/skip/tutorial",
  FILTERS_META: "/invoice/filters-meta",

  // Referral
  FETCH_REFERRER_DETAILS: "/api/referral/referrer-details",
  FETCH_REFERRER_DETAILS_VIA_CODE: "/api/referral/referrer-details-via-code",
  FETCH_REFERRAL_TRACKING_DATA: "/api/referral/referral-tracking",
  FETCH_REFERRAL_TRACKING_DATA_VIA_IDENTIFIER: "/api/referral/referral-tracking-via-identifier",
  FETCH_REFERRAL_METRICS: "/referral/metrics",
  // Alexa end-date is per-user (activation + 15 days). Only Alexa
  // overrides the static endDate from `campaigns.config.ts`.
  FETCH_ALEXA_15DAYS_ELIGIBILITY: "/referral/alexa-campaign-eligibility",
  FETCH_INVOICE_COUNT: "/api/route?path=invoice/invoice_count",
  SKIP_REFERRAL_BANNER: "/referral/banner/skip",
  CLAIM_REFERRAL_REWARD: "/referral/claim",
  REWARD_STATUS: "/reward-status/test-txn-experiment",
  // Multi User
  GET_USER_LIST: "user/management/list",
  ADD_SECONDARY_USER: "/user/management/link/secondary-user",
  REMOVE_SECONDARY_USER: "/user/management/delink",

  // CMS
  CMS_CURRENCY: "/api/cms/currency",
  GET_CURRENCIES: "/api/currencies?populate=*",

  // Notifications
  NOTIFICATIONS_TRAY: "/api/notification/tray",
  GET_USER_LEVEL_NOTIFICATIONS: "/api/notification",
  INCREMENT_EXPORTER_MILESTONE_POPUP_COUNT: "/milestone/incrementMilestoneShowCount",
  GET_NOTIFICATIONS_TRAY:
    "/api/feature-trays?populate[0]=cta&populate[1]=image&populate[2]=image.image&sort=date:desc&pagination[start]=0&pagination[limit]=8",
  GET_NOTIFICATION_CLICK: "user/action/notification",
  SET_NOTIFICATION_CLICK: "/user/action/notification",
  NOTIFICATION_WIDGET: "/api/notification/widget",
  FETCH_REWARD_TNC: "/reward-status/fetch-tnc",
  GET_NOTIFICATION_WIDGET:
    "/api/feature-widgets?populate[0]=image&populate[1]=image.image&populate[2]=cta&sort[0]=publishedAt:desc",
  GET_NOTIFICATION_WIDGET_ACTION: "user/action/widget/{id}",
  SET_NOTIFICATION_WIDGET_ACTION: "/user/action/widget",

  PROSPECT_INVOICE_DETAILS: "graphql/prospect/challan",
  UPDATE_PROSPECT_INVOICE_LOGO: "/prospect-challan/update/invoice/logo",
  CREATE_PROSPECT_INVOICE: "prospect-challan/create/invoice",
  VERIFY_PROSPECT_USER_GSTIN: "prospect-challan/gstin/details/:gstin",

  PROSPECT_UPDATE_BILL_FROM: "prospect-challan/update/bill/from",
  PROSPECT_UPDATE_BILL_TO: "prospect-challan/update/bill/to",
  PROSPECT_UPDATE_INVOICE_ITEMS: "/prospect-challan/update/items",
  PROSPECT_UPDATE_BANK_ACCOUNT: "/prospect-challan/update/bankaccount",
  PROSPECT_UPDATE_BANK_ACCOUNT_FROM_ITEMS: "/prospect-challan/items/update/bankaccount",
  PROSPECT_UPDATE_OTHER_DETAILS: "/prospect-challan/update/other/details",
  PROSPECT_GET_PLACE_OF_SUPPLY: "/prospect-challan/state/from/:pinCode",
  UPDATE_PROSPECT_BANK_ACCOUNT_DETAILS: "/api/create-invoice/update-bank-details",
  CREATE_BUSINESS_BANK_ACCOUNT: "/prospect-challan/create/bankaccount",
  CREATE_BUSINESS_BANK_ACCOUNT_CHALLAN: "challan/create/bankaccount",
  UPLOAD_SIGNATURE: "challan/sign/upload",
  UPLOAD_SIGNATURE_PROSPECT: "prospect-challan/sign/upload",
  DELETE_LUT: "challan/delete/lut",
  DELETE_LUT_PROSPECT: "prospect-challan/delete/lut",
  DELETE_SIGNATURE: "challan/sign/delete",
  DELETE_SIGNATURE_PROSPECT: "prospect-challan/sign/delete",

  ZOHO_BOOKS: {
    AUTHENTICATE: "khata/authenticate",
    SET_PRIMARY_ORG: "khata/mark/zoho/org/primary",
    GET_CONNECTION_STATUS: "khata/get/zoho/connection/status",
    SYNC_DATA: "khata/sync/data/user",
    SKIP_ZOHO_SYNC: "khata/skip/zoho/sync",
    DISCONNECT: "khata/revoke/access",
    LAST_SYNC_DATE: "khata/last/sync/date",
    GET_SKIP_ZOHO_SYNC: "khata/get/skip/zoho/sync",
    GET_ZOHO_CONNECT_URL: "khata/get/zoho/connect/url",
    GET_ZOHO_SYNC_FREQUENCY: "khata/get/sync/frequency",
    GET_ALLOW_INR_INVOICES: "khata/get/allow_inr_invoices",
    SET_ALLOW_INR_INVOICES: "khata/set/allow_inr_invoices",
  },

  SET_USER_DASHBOARD_VISIT: "/user/action/dashboard/visit",
  USER_ACTION_MARK: "/user/action/mark",

  CREATE_AUD_VA: "/aud/create_virtual_account",
  CHECK_AUD_ACCOUNT_STATUS: "/aud/get_virtual_account",

  GET_BANNER_LIST: "/banner/get/list",
  SKIP_BANNER: "/banner/skip",
  PAYPAL_DISCONNECT_ROUTE: "paypal/onboarding/delete",
  PAYPAL_SKIP_ROUTE: "paypal/skip/paypal",
  PAYPAL_ONBOARDING_UPDATE_ROUTE: "paypal/onboarding/update",
  CREATE_ORDER_PAYPAL: "paypal/create-order/:paymentLinkId",
  CAPTURE_PAYMENT_LINK_ORDER: "paypal/capture-payment-link-order/:orderId",
  MARK_PAYMENT_LINK_UNPAID: "paypal/mark-payment-link-unpaid/:paymentLinkId",
  MARK_PAYMENT_LINK_PAID: "paypal/mark-payment-link-paid/:paymentLinkId",
  INITIATE_PAYPAL_ONBOARDING: "/paypal/onboarding/initiate",

  FETCH_VKYC: "swagat/api/fetch/vkyc_link",
  GENERATE_VKYC: "swagat/api/generate/vkyc_link",
  FETCH_UDYAM_OCR_STATUS: "swagat/api/fetch/udyam",
  SUBMIT_UDYAM_OCR: "swagat/api/udyam/ocr",
  FETCH_PROFILE: "swagat/api/fetch/vkyc_profile/:profileId",

  VERIFY_IEC_CODE: "swagat/api/verify/iec",

  CREATE_DBS_SG_VA: "/dbs/sg/create/virtual/account",

  SG_ACCOUNT_STATUS: "/dbs/sg/get/virtual/account/status",
  GLOMO_ACCOUNT_STATUS: "/glomo/get/virtual/account/status",
  GET_UAE_ACCOUNT_STATUS: "/uae-aed/check/va_status",

  WHATSAPP_OPT_IN: "/whatsapp/opt/in",
  UPLOAD_MCA_DOCUMENT: "/swagat/api/upload/mca-docs",
  GET_FEATURE_WIDGET_DETAILS: "/reward-status/feature-widget-details",

  PAYMENT_LINKS_CONNECTION_STATUS: "/payment-link/connection-status",
  DELETE_PAYMENT_LINK: "/payment-link/delete",
  CREATE_ORDER_PAYMENT_LINK: "/payment-link/create-order",
  GET_IMPORTER_PAYMENT_PREFERENCES: "/payment-link/importer-preferences/:importerId",
  PPRO_ONBOARDING_INITIATE: "/ppro/onboarding/initiate",
  PPRO_VALIDATE_REDIRECT: "/ppro/validate/redirect",

  SEND_INTERNATIONAL_ACCOUNTS_EMAIL: "/dashboard/send-international-accounts-email",
  FOCUSED_HOME_STATE: "/focused/home/get/state",
  FOCUSED_HOME_EXPORTER_USE_CASE: "/focused/home/get/exporter/use/case",
  FOCUSED_HOME_CONGRATS: "/focused/home/show/congrats/pop/up",
  FOCUSED_HOME_CONGRATS_SEEN: "/focused/home/mark/congrats/pop/up/seen",
  FOCUSED_HOME_CONTINUE_INT_ACC: "/focused/home/continue/int/account",
  FOCUSED_HOME_GET_HOME_STATE: "/focused/home/get/home/state",
  EMAIL_NOTIFICATION_SETTINGS: "/transaction/comms/email/subscription",

  UPSERT_IMPORTER: "/dashboard/upsert/importer",

  PUBLIC_EVENTS_TRACK: "/analytics/track/public",
  NPS: {
    FETCH_NPS_DATA: "/nps/fetch/data",
    SAVE_NPS_RESPONSE: "/nps/save/response",
    MARK_SEEN: "/nps/mark/seen",
  },

  INTERNATIONAL_ACCOUNT_PREFERENCE: "/dashboard/international-account-preference",
  SET_LAST_VIEWED_ACCOUNT: "/dashboard/last-viewed-account",

  FETCH_VARIANTS: "/abtest/fetch/variants",
  SUBMIT_ENTITY_TYPE: "/swagat/api/submit/business_type",
  SUBMIT_PROOF_FOR_SENDER_CASE: "/nigrani/submit/proof/sender/case",

  DASHBOARD_VERSION: "/dashboard/version/get",

  VALIDATE_PDF_PASSWORD: "/swagat/api/validate-pdf-password",
  CHECK_PDF_PASSWORD: "/swagat/api/check-pdf-password",
  // Self-serve email / phone change (munshi)
  ACCOUNT_CHANGE_INITIATE: "/swagat/api/account-change/initiate",
  ACCOUNT_CHANGE_VERIFY_CURRENT: "/swagat/api/account-change/:requestId/current/verify",
  ACCOUNT_CHANGE_RESEND_CURRENT: "/swagat/api/account-change/:requestId/current/resend",
  ACCOUNT_CHANGE_SUBMIT_NEW: "/swagat/api/account-change/:requestId/new",
  ACCOUNT_CHANGE_VERIFY_NEW: "/swagat/api/account-change/:requestId/new/verify",
  ACCOUNT_CHANGE_RESEND_NEW: "/swagat/api/account-change/:requestId/new/resend",
  ACCOUNT_CHANGE_ABANDON: "/swagat/api/account-change/:requestId/abandon",
  ACCOUNT_CHANGE_IDENTITY_INITIATE: "/swagat/api/account-change/:requestId/identity/initiate",
  ACCOUNT_CHANGE_IDENTITY_COMPLETE: "/swagat/api/account-change/:requestId/identity/complete",

  EBRC_BASIC_DETAILS: "dgft/ebrc/details",
  EBRC_GRAPHQL: "/graphql/ebrc",
  FETCH_PAST_IRM: "dgft/fetch/past-irm",
  RESEND_EBRC_APPROVAL_EMAIL: "dgft/resend/ebrc/email",
  RESEND_FIRA_MAPPING_EMAIL: "edpms/fira/mapping-email/resend",
  FIRA_GET_STARTED: "edpms/fira/get-started",
  CHECK_CONNECTION_STATUS: "dgft/check-and-activate/dgft-config",
  UPLOAD_DGFT_CONFIG: "dgft/upload/config/exporter",
  UPLOAD_SHIPPING_BILLS: "dgft/upload/shipping-bill/exporter",
  CREATE_MAPPING: "dgft/create-mapping/exporter",
  // FIRA/EDPMS routes
  EDPMS_GRAPHQL: "/graphql/edpms",
  CREATE_FIRA_MAPPING: "edpms/fira/create-mapping/exporter",

  CREATE_PLAID_ATTEMPT: "/payment-link-payer/create-plaid-attempt",
  AUTHENTICATE_PLAID_ATTEMPT: "/payment-link-payer/authenticate-plaid-attempt",
  ACCEPT_PLAID_ATTEMPT: "/payment-link-payer/accept-plaid-attempt",
  REJECT_PLAID_ATTEMPT: "/payment-link-payer/reject-plaid-attempt",
  SEND_SLACK_NOTIFICATION: "/comms/slack/send_message",

  SKIP_INSTA_LINK_BANNER: "insta/link/skip/banner",
  CARD_WAITLIST: "insta/link/join/waitlist",
  INSTA_LINK_REQUEST: "insta/link/request",
  INSTA_LINK_REQUEST_STATUS: "insta/link/request/status",

  GET_VEEM_DETAILS: "/payment-link-payer/veem/get/details",
  ADD_CARD: "/payment-link-payer/veem/submit/card/details",
  MAKE_CARD_ACTIVE: "/payment-link-payer/veem/make/card/active",
  PHASE_RELEASE_ELIGIBILITY: "/phase-release-manager/exporter_eligible",
  PSP_CUSTOMER_DATA: "/api/psp/v1/spi/customerdata",
  BLACK_LIST_ELIGIBILITY: "/phase-release-manager/exporter_blacklist",

  SUBMIT_PAYMENT_METHOD_FOCUSED_HOME: "/focused/home/set/payment/method",
  SUBMIT_PAYMENT_TIMELINE_FOCUSED_HOME: "/focused/home/set/payment/timeline",
  MARK_CONFETTI_SHOWN: "/focused/home/set/confetti/shown",
  MARK_RECEIVE_PAYMENT_CONTINUED: "/focused/home/set/first/payment/clicked",
  REMOVE_RECEIVE_PAYMENT_CONTINUED: "/focused/home/remove/first/payment/clicked",

  // UAE AED Pricing Routes
  UAE_AED_PRICING_POPUP_STATUS: "/uae-aed/pricing/check-popup-status",
  UAE_AED_CHECK_ACCOUNT_ACCESS: "/uae-aed/check-account-access",

  // UAE Banner Routes
  UAE_BANNER_STATUS: "/uae-aed/banner/check-status",
  UAE_BANNER_DISMISS: "/uae-aed/banner/dismiss",

  // IP Registry Routes
  IP_REGISTRY_ADD: "/ip-registry/add",
  UAE_GLOMO_PAY_MERCHANT_CREATE: "/glomo_pay/merchant/create",
  UAE_ACCOUNT_FEEDBACK: "/glomo_pay/account/feedback",

  SKIP_MOBILE_MAPPING_BANNER: "/dashboard/skip/mobile-mapping-banner",
  PAYER_BENEFICIARY_LINKING: "payer-beneficiary/link",
  PAYER_BENEFICIARY_LINKING_CHECK: "payer-beneficiary/link/check",
};

export const BFF_ROUTES = {
  // UAE Banner BFF Routes
  UAE_BANNER_CHECK_STATUS: "/api/uae-banner/check-status",
  UAE_BANNER_DISMISS: "/api/uae-banner/dismiss",

  // UAE Glomo Pay Merchant BFF Routes
  UAE_GLOMO_PAY_MERCHANT_CREATE: "/api/vaccount/create-aed-accounts",
  UAE_ACCOUNT_FEEDBACK: "/api/vaccount/uae-account-feedback",

  LOGIN_LINK_PROSPECT_USER: "/api/create-invoice/login-prospect-user",
  GET_CHALLAN_COUNTS: "/api/create-invoice/count",
  VALIDATE_URL: "/api/route/validate_url",
  FETCH_TNC: "/api/reward/tnc",
  SEND_PC_EMAIL: "/api/payment-confirmation/email",
  FILE_UPLOAD: "/api/route/file",
  FETCH_ACTIVE_REFERRAL: "/api/referral/active-campaign",
  FETCH_ACTIVE_REFERRAL_PUB: "/api/referral/active-campaign-pub",
  FETCH_MILESTONE_PROGRESS: "/api/referral/milestone-progress",
  FETCH_ALEXA_15DAYS_ELIGIBILITY: "/api/referral/alexa-15-days-eligibility",
  FETCH_REFERRAL_METRICS: "/api/referral/metrics",
  SAVE_EMAILS: "/api/payment-confirmation/save-emails",
  TOGGLE_EMAIL_CONFIG: "/api/payment-confirmation/toggle-config",
  REWARD_STATUS_FOR_TEST_TXN: "/api/reward/test-txn-campaign",
  CREATE_PROSPECT_INVOICE: "/api/create-invoice/create-prospect-invoice",
  CAPTURE_INVOICE_LEAD: "/api/create-invoice/capture-lead",
  CAPTURE_SOLE_PROP_DECLARATION: "/api/declaration",
  BFF_GET_PREFERRED_EMAILS_FOR_IMPORTER: "/api/payment-confirmation/preferred-emails",
  CREATE_AUD_VA: "/api/aud/create-account",
  GET_AUD_VA_STATUS: "/api/aud/get-account-details",
  SKIP_REFERRAL_BANNER: "/api/referral/skip-banner",
  CLAIM_REFERRAL_REWARD: "/api/referral/claim",
  FETCH_VKYC: "/api/vkyc",
  FETCH_UBOS: "/api/vkyc/ubo",
  SUBMIT_VKYC_DECLARATION: "/api/vkyc/declaration",
  VERIFY_BANK_ACCOUNT: "/api/bank-account/verify",
  ACTIVATE_BANK_ACC: "/api/bank-account/activate",
  NEFT_IN_PROGRESS: "/api/bank-account/neft-in-progress",
  FETCH_UDYAM_OCR_STATUS: "/api/udyam",
  SUBMIT_UDYAM_OCR: "/api/udyam/ocr",
  FETCH_VKYC_PROFILE: "/api/vkyc/profile",
  GENERATE_VKYC_LINK: "/api/vkyc/generate",
  GET_BANNER_LIST: "/api/banner-list",
  SKIP_BANNER: "/api/banner/skip",
  CREATE_DBS_SG_VA: "/api/vaccount/create-sgd-account",
  FETCH_VA_DETAILS: "/api/vaccount/get-all-account-details",
  FETCH_SG_ACCOUNT_STATUS: "/api/vaccount/fetch-sg-account-status",
  GET_FOCUSED_HOME_DATA: "/api/focused-home",
  GET_CONGRATS_POP_UP: "/api/congrats-pop-up",
  MARK_CONGARTS_POP_UP_SEEN: "/api/congrats-pop-up/mark-seen",
  SET_LAST_VIEWED_ACCOUNT: "/api/vaccount/last-viewed-account",
  GET_EXPORTER_MILESTONES: "/api/exportermilestones",
  INCREMENT_EXPORTER_MILESTONE_POPUP_COUNT: "/api/exportermilestones/increment-popup-show-count",
  GET_EXPORTER_LEVEL_NOTIFICATIONS: "/api/exporter-level-notifications",
  MARK_USER_SKIP_ACTION_DONE: "/api/exporter-level-notifications/mark-notification-shown",
  CHECK_USER_SKIP_ACTION_DONE: "/api/exporter-level-notifications/check-notification-shown",
  INVOICES_LIST_DATA: "/api/invoices",
  EXPORTER_INFO: "/api/invoices/exporter_info",
  CLIENT_LIST: "/api/client-list",
  REPORT_DOWNLOAD: "/api/reports/download",
  REPORT_AVAILABILITY: "/api/reports/availability",
  FETCH_VARIANTS: "/api/ab-test/variants",
  FETCH_COUNTRIES: "/api/countries",
  FETCH_EXPORTER_ONBOARDING_STATE: "/api/route/authorization_validator",
  FETCH_IRM_HDFC_HOME: "/api/ebrc/irm-hdfc",
  REQUEST_PAST_IRM: "/api/ebrc/past-irm",
  FETCH_IRM_NON_HDFC_HOME: "/api/ebrc/irm-non-hdfc",
  // FIRA BFF routes
  FETCH_FIRA_HOME: "/api/edpms/fira-home",
  CREATE_FIRA_MAPPING: "/api/edpms/fira-mapping",
  SEND_SLACK_NOTIFICATION: "/api/slack/send_message",
  RECENT_PAYMENT_MOBILE_DATA: "/api/recent-payments",
  GENERATE_PAYMENT_LINK: "/api/payment-link/generate",
  // Balance withdraw (client → BFF)
  WITHDRAW_INITIATE: "/api/balance-withdraw/initiate",
  WITHDRAW_PROCESS: "/api/balance-withdraw/process",
  // Draft payout (make payout flow)
  CREATE_DRAFT_PAYOUT: "/api/balance-payout/draft-create",
  USER_ACTION_STATUS: "/api/user-action/status",
  USER_ACTION_MARK: "/api/user-action/mark",
};

export const CHALLAN_ROUTES = {
  LINK_PROSPECT_USER: "challan/link/prospect/invoice",
  GET_NUMBER_OF_RECURRING_CONFIGS: "challan/number/recurring-config",
  DELETE_RECURRING_CONFIG: "challan/recurring/delete",
  GET_RECURRING_CONFIG_JOB_ID: "challan/recurring/recurring-invoice-configs/:invoiceId",
};

export default BE_ROUTES;
