import { InvoiceState, UnitType, PaymentLinkMethod } from "../../constants/newinvoiceConstants";
import { ResponseWrapper } from "../../authentication/api/AuthApiDto";

export type InvoiceSeller = {
  id: number;
  name: string;
  website?: string;
  phoneNumber: string;
  email: string;
  address: string;
  gstin: string;
  gstinState?: string;
  pincode?: string;
  companyLogoUrl: string;
  isCompleted: boolean;
  gstinVerified?: boolean;
  gstinNotAvailable?: boolean;
  businessPan?: string;
};

export type InvoiceBuyer = {
  id: number;
  name: string;
  address: string;
  gstin?: string;
  gstinNotAvailable?: boolean;
  gstinVerified?: boolean;
  gstinState?: string;
  placeOfSupply?: string;
  pincode: string;
  importerId?: number;
  isCompleted: boolean;
  countryMaster?: CountryMaster;
};

export type InvoiceFinancial = {
  id: number;
  currency: string;
  subTotal: number;
  discountPercentage: number;
  discountValue: number;
  platformFees: number;
  igstApplicable: boolean;
  totalIgst: number;
  totalCgst: number;
  totalSgst: number;
  roundOff: boolean;
  itemTotal: number;
  total: number;
  isCompleted: boolean;
  unit: UnitType;
  isSacPresent: boolean;
  isDescriptionRequired: boolean;
};

export type InvoiceItem = {
  id?: number;
  name: string;
  description?: string;
  sac?: string;
  unit: string;
  quantity: number;
  rate: number;
  total: number;
  currency: string;
  cgst?: number;
  sgst?: number;
  igst?: number;
  igstApplicable?: boolean;
};

export type SkydoBankAccount = {
  id: number;
  bankLogoUrl: string;

  accountNumber: string;
  routingCodeType: string;
  paymentType: string;
  routingNumber: string;
  bankName: string;
  currency?: string;
  bankAddress: string;
  accountProvider?: string;
  accountRole?: string;
};

export type BusinessBankAccount = {
  id: number;
  accountHolderName: string;
  accountNumber: string;
  ifscCode: string;
  bankName: string;
  bankLogoUrl: string;
  address: string;
  iban: string;
  swiftCode: string;
};

export type UaePassOnFeeType = "full" | "base" | "regional";

export type InvoiceBankAccount = {
  id: number;
  bankType: string;
  skydoBankType?: string;
  skydoBankAccount?: SkydoBankAccount;
  businessBankAccount?: BusinessBankAccount;
  isCompleted: boolean;
  currency: string;
  paymentLinkMethod?: PaymentLinkMethod;
  paymentLink?: string;
  passOnBankFee?: number;
  passOnCardsFee?: number;
  passOnNetBankingFee?: number;
  /** Type of pass-on fee when client bank account country is UAE; null for other countries */
  uaePassOnFeeType?: UaePassOnFeeType | null;
};

export type InvoiceOtherDetail = {
  id: number;
  notes: string;
  lut?: string;
  others?: { [key: string]: string };
  isCompleted: boolean;
  signatureUrl?: string;
};

export type InvoicePaymentTerm = {
  id: number;
  paymentTerms: string;
  invoiceDate: string;
  dueDate?: string;
};

export type InvoiceProgress = {
  completed: boolean;
  sectionName: string;
  sectionOrder: number;
};

export type ChallanClient = {
  id: number;
  name: string;
  country: string;
  pincode: string;
  gstin?: string;
  address: string;
};

export type GST = {
  id: number;
  gstin: string;
  entryType: string;
  authStatus: string;
  address: string;
  nba: string;
};

export type InvoiceSequenceDto = {
  invoiceNumber: string;
  lastInvoiceNumber?: string;
};

export type EInvoiceCredentials = {
  gstin: string;
  username: string;
  password: string;
};

export type CountryMaster = {
  id: number;
  name: string;
};

export type SacMaster = {
  id: number;
  code: string;
  taxRate?: number;
};

export type EInvoice = {
  irn: string;
  irnTimestamp: string;
  signedQrCode: string;
};

export type Cache = {
  challanClients: ChallanClient[];
  gstList: GST[];
  invoiceItems: InvoiceItem[];
  skydoBankAccounts: SkydoBankAccount[];
  businessBankAccount: BusinessBankAccount;
  generatedInvoiceNumber: string;
  invoiceSequence: InvoiceSequenceDto;
  einvoiceCredentialsList: EInvoiceCredentials[];
  countryMasterList: CountryMaster[];
  sacMasterList: SacMaster[];
  anyInvoiceFinalized: boolean;
  skydoFeeBufferValue: number;
  userSignature?: string;
  lastManualInvoiceNumber?: string;
  previousInvoiceDetails?: PreviousInvoiceDetails;
  businessPan?: string;
};

export type PreviousInvoiceDetails = {
  lastAutoGeneratedInvoiceNumber?: string;
  lastManualInvoiceNumber?: string;
  lastInvoiceNumberType: InvoiceNumbGenStrategy;
};

export enum InvoiceNumbGenStrategy {
  AUTO = "AUTO",
  MANUAL = "MANUAL",
}

export type RecurringInvoiceConfigDto = {
  id: number;
  frequency: string;
  startDate: string;
  active: boolean;
};

export type DraftInvoiceGQLResponse = {
  id: number;
  invoiceState: InvoiceState;
  invoiceFinancial: InvoiceFinancial;
  invoiceBuyer: InvoiceBuyer;
  invoiceSeller: InvoiceSeller;
  invoiceBankAccount: InvoiceBankAccount;
  invoiceOtherDetail: InvoiceOtherDetail;
  invoiceItems: InvoiceItem[];
  invoiceNumber: string;
  invoicePaymentTerm: InvoicePaymentTerm;
  invoiceProgress: InvoiceProgress[];
  fileName: string;
  eInvoice: EInvoice;
  recurringInvoiceConfig?: RecurringInvoiceConfigDto;
};

export type InvoiceDocType = {
  logoUrl: string;
  invoiceFinancial: InvoiceFinancial;
  invoiceBuyer: InvoiceBuyer;
  invoiceSeller: InvoiceSeller;
  invoiceBankAccount: InvoiceBankAccount;
  invoiceOtherDetail: InvoiceOtherDetail;
  invoiceItems: InvoiceItem[];
  invoiceNumber: string;
  invoicePaymentTerm: InvoicePaymentTerm;
  businessLegalName: string;
  skydoBankAccounts: SkydoBankAccount[];
  isDraft: boolean;
  qrCodeSrc?: string;
  eInvoice?: EInvoice;
  /** Optional: when set, "View details" in UAE transfer section becomes a link to this URL (public importer page) */
  uaeTransferDetailsUrl?: string;
};

export type GSTList = { [key: string]: any }[];

export type GSTINVerificationResponse = {
  gstin: string;
  address: string;
  businessName?: string;
};

export type BankAccountInputDto = {
  name: string;
  accountNumber: string;
  accountNumberHidden: string;
  ifscCode: string;
};

export interface PaymentLinkData {
  paymentLink: string;
}

export interface PaymentLinkResponse {
  success: boolean;
  data: PaymentLinkData;
}

export type FinaliseInvoiceFormDto = {
  invoiceNumberType: InvoiceNumberType;
  invoiceNumber?: string;
  manualInvoiceNumber?: string;
  invoiceDate: string;
  paymentTerms: string;
  dueDate: string;
  recurringStartDate: string;
  recurringFrequency?: string;
  enableRecurringInvoice?: string;
};

export type FinaliseInvoiceConfigDto = {
  invoiceBlob: Blob;
  id: number;
  formValues: FinaliseInvoiceFormDto;
  onSuccess?: () => void;
  onError?: () => void;
  invoiceNumber: string;
  paymentLinkUrl?: string; // Payment link URL to be stored in backend
  originalInvoiceNumber?: string; // Original invoice number when editing an existing invoice
  originalInvoiceId?: number; // Original invoice ID when editing an existing invoice
};

export type UpdateEInvoiceConfigDto = {
  invoiceBlob: Blob;
  id: number;
  onSuccess: (data: ResponseWrapper<number>) => void;
  onError: (e: ResponseWrapper<string>) => void;
};

export enum InvoiceNumberType {
  AUTO,
  MANUAL,
}

export enum RepeatInterval {
  EVERY_TWO_WEEKS = "EVERY_TWO_WEEKS",
  EVERY_MONTH = "EVERY_MONTH",
  EVERY_TWO_MONTHS = "EVERY_TWO_MONTHS",
  QUARTERLY = "QUARTERLY",
}

export type ChallanCountDto = {
  draftInvoiceCount?: number;
  recurringInvoiceConfigCount?: number;
};

export type OtherDetailsFormValues = {
  showNotesInput: boolean;
  showLutInput: boolean;
  showAddSignature: boolean;
  showAddCustomFields: boolean;
  notes?: string;
  lut?: string;
  others?: {
    label: string;
    value?: string;
  }[];
  includeLut: boolean;
  includeSignature: boolean;
};

export type PdfInstanceType = {
  blob: Blob;
  url: string;
};
